### ISSUE TITLE
GPU leasing failing

### ISSUE THREAD

**Issue by harsha5500** [kthcloud/console#189]
**Describe the bug**
Unable to lease available and free GPUs. 

**To Reproduce**
1. Go to Admin tool -> Choose user Harsha -> Vm Per
2. Lease GPU RTX A5000
4. No error, the GPU is not attached. No error message.

Would be nice to see logs if available for the console app when GPU requests are initiated.

**Comment by pierrelefevre** [comment]
@harsha5500 bug is tracked go-deploy, console repo only houses the frontend code. 

See https://github.com/kthcloud/go-deploy/issues/421

**Comment by pierrelefevre** [comment]
The issue is such that we don't get any error from cloudstack, just a 500 type "something went wrong" but I agree it should probably toast a snackbar telling the user it didn't attach.

I'm surprised you can't see it in the async job banner at the bottom, next to attach GPU should say "Failed" but perhaps the error is occurring after we already think it's done

**Comment by harsha5500** [comment]
Ah just to clarify. Yes the async job banner does report the job failed. For a normal user it's absolutely fine.

But I am unable to find information that I can use to debug. I understand the limitation of Cloud Stack. 

Will close this issue and continue of go-deploy for the GPU issue.
