### ISSUE TITLE
Improve GPU leasing UX flow

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/console#242]
The GPU lease UX is pretty clunky right now, so it should be improved. Add any thoughts to this issue as comments to discuss how the flow can be smoother.

**Comment by pierrelefevre** [comment]
#255 Groups the GPU by name, cleaning up the list a bit.

**Comment by Phillezi** [comment]
Hi, 
maybe changing the "Wait in line" button to a "Request access" that links to [docs /usage/gpu/#requesting-an-upgrade](https://docs.cloud.cbh.kth.se/usage/gpu/#requesting-an-upgrade) or the discord server if the user doesn't have "useGpus" in their `user.role.permissions` array, might be something to change.

Since users without permissions just get this right now:
![Screencast-from-2024-06-01-20-39-34](https://github.com/kthcloud/console/assets/112874974/4d6dc933-9abc-45f1-8548-7fc2d6334673)

**Comment by pierrelefevre** [comment]
Request access sounds like much better wording! I think it might just be better to hide the Gpu lease page and button if a user doesn't have the permission?

**Comment by Phillezi** [comment]
Oh yeah, might be better to just not allow access to the page instead

**Comment by pierrelefevre** [comment]
Closing for now, any small improvements can be created as separate issues in the future
